/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#3a494b',
        'on-background': '#e5e2e1',
        'on-secondary-fixed-variant': '#005230',
        'secondary-fixed': '#55ffa9',
        'on-secondary': '#00391f',
        'surface-container-low': '#1c1b1b',
        'tertiary-fixed-dim': '#d1bcff',
        'error': '#ffb4ab',
        'surface-container-highest': '#353534',
        'on-error-container': '#ffdad6',
        'surface-container-lowest': '#0e0e0e',
        'surface-container': '#201f1f',
        'on-secondary-fixed': '#002110',
        'on-primary-container': '#006b71',
        'tertiary': '#fdf6ff',
        'inverse-surface': '#e5e2e1',
        'inverse-primary': '#00696f',
        'secondary': '#f5fff4',
        'on-primary-fixed': '#002022',
        'surface': '#131313',
        'secondary-fixed-dim': '#00e38d',
        'on-primary-fixed-variant': '#004f53',
        'primary-fixed-dim': '#00dce6',
        'on-secondary-container': '#007144',
        'surface-variant': '#353534',
        'surface-container-high': '#2a2a2a',
        'surface-bright': '#3a3939',
        'on-surface-variant': '#b9cacb',
        'surface-dim': '#131313',
        'on-tertiary-fixed-variant': '#5700c9',
        'outline': '#849495',
        'background': '#131313',
        'on-primary': '#00373a',
        'on-tertiary-fixed': '#23005b',
        'primary-fixed': '#6ff6ff',
        'inverse-on-surface': '#313030',
        'tertiary-fixed': '#e9ddff',
        'primary': '#e3fdff',
        'tertiary-container': '#e4d5ff',
        'surface-tint': '#00dce6',
        'on-tertiary-container': '#741bff',
        'on-surface': '#e5e2e1',
        'secondary-container': '#11ffa0',
        'primary-container': '#00f3ff',
        'on-tertiary': '#3c0090',
        'error-container': '#93000a',
        'on-error': '#690005',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
